kind: Deployment
apiVersion: apps/v1
metadata:
  name: horme
  labels:
    app: horme
    component: microservice
spec:
  selector:
    matchLabels:
      app: horme
      component: microservice
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  progressDeadlineSeconds: 300
  template:
    metadata:
      name: horme
      labels:
        app: horme
        component: microservice
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - name: horme
        image: 23030112/horme
        readinessProbe:
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /health_check
            port: horme
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sleep", "20" ]
        env:
          - name: NODE_ENV
            value: dev
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits: {}
        imagePullPolicy: Always
        ports:
        - name: horme
          containerPort: 3000
      volumes:
        - name: regsecret
          secret:
            secretName: regsecret
      nodeSelector:
        agentpool: nodepoolho